### ISSUE TITLE
I want to ask a question. In ETA model, is long_term id shared embedding with short_term id? Thank you!

### ISSUE THREAD

**Issue by ShaominFan** [i-Jayus/RecSystem-Pytorch#4]
class ETA(nn.Module):
....
def forward(self,user,item,long_term,short_term):
        """
        :param user: user id
        :param item: item id
        :param long_term: long-term behavior sequence
        :param short_term: short-term behavior sequence
        """
        user = torch.flatten(self.user_embedding(user))
        item = torch.flatten(self.item_embedding(item))
        hashed_item = self.hashing(item)
        long_item = []
        for i in range(len(long_term)):
            long_item.append(torch.flatten(self.item_embedding(long_term[i])))

        short_item = []
        for i in range(len(short_term)):
            short_item.append(torch.flatten(self.item_embedding(short_term[i])))
...

**Comment by i-Jayus** [comment]
Yes, the same item shares the same item id.
